#!/bin/bash

emacs --batch --eval '(byte-compile-file "./ifdef.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./highlight-symbol.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./ibus.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./highlight-parentheses.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./shebang.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./shell-pop.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./desktop-menu.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./autopair.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./xgtags.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-cmd.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icomplete+.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-menu.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-fn.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-opt.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-mac.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-mcmd.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-face.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-var.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./icicles/icicles-mode.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+-mac.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+-1.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+-key.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+-lit.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+-doc.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+-bmu.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bookmarkplus/bookmark+-chg.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./eval-after-load.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./mic-paren.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./color-theme.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./themes/color-theme-blackboard-orig.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./themes/color-theme-example.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./themes/color-theme-blackboard.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./themes/color-theme-library.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./session.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./smooth-scrolling.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./smali-mode.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./hide-region.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./smart-compile.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./tempo-snippets.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./bm.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./ppindent.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./hide-comnt.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./gtags.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./tabbar.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./xcscope.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./highline.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./irfc.el")' || exit 1
emacs --batch --eval '(byte-compile-file "./column-marker.el")' || exit 1
