;;; color-theme
(require 'color-theme)
(color-theme-initialize)
;(load-file "~/emacs/elisp/themes/color-theme-blackboard-orig.el")
;(load-file "~/emacs/elisp/themes/color-theme-blackboard.el")
;(color-theme-tty-dark)
;(color-theme-goldenrod)
;(color-theme-billw)
;(color-theme-lethe)
;(color-theme-comidia)
;(color-theme-white-on-black)
;(color-theme-gnome2)
(color-theme-charcoal-black)
;(color-theme-blackboard)